apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: shuttle-apps
spec:
  type: ExternalName
  externalName: host.docker.internal  # Points to your laptop/host machine (Docker Desktop)
  ports:
    - port: 9100        # Port exposed inside Kubernetes
      targetPort: 9000  # Default MinIO port running on Docker
      protocol: TCP
